apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
  namespace: site
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker2
      containers:
        - name: mysql-service
          image: mysql:8.0
          envFrom:
            - configMapRef:
                name: newsum-db-config
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-storage
        resources:
          requests:
            storage: 10Gi
